# Window settings
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

# Player settings
PLAYER_MAX_HEALTH = 100
PLAYER_THRUST_SPEED = 0.5  # Thrust speed for rotation control
PLAYER_DIRECT_SPEED = 3.0  # Movement speed for directional control
PLAYER_ROTATION_SPEED = 0.1  # How fast the ship rotate
PLAYER_FRICTION_ROTATION = 0.95
PLAYER_FRICTION_DIRECT = 0.7
PLAYER_SIZE = 60
PLAYER_SHOOT_COOLDOWN = 15  # frames
PLAYER_COLLISION_RADIUS = 15

# Enemy settings
ENEMY_HEALTH = 20
ENEMY_SPEED = 1.0
ENEMY_SPEED_INCREASE_PER_PHASE = 0.2
ENEMY_SIZE = 50
ENEMY_COLLISION_RADIUS = 20
ENEMY_COLLISION_DAMAGE = 5

# Spawner settings
SPAWNER_HEALTH = 30
SPAWNER_HEALTH_INCREASE_PER_PHASE = 10
SPAWNER_SIZE = 100
SPAWNER_COLLISION_RADIUS = 30
SPAWNER_SPAWN_RATE = 60  # frames
SPAWNER_SPAWN_RATE_DECREASE = 5  # faster spawning per phase
SPAWNER_MIN_SPAWN_RATE = 30
SPAWNER_MIN_COUNT = 2
SPAWNER_MAX_COUNT = 6

# Projectile settings
BULLET_SPEED = 8
BULLET_DAMAGE = 10
BULLET_SIZE = 70
BULLET_COLLISION_RADIUS = 8

# Game settings
MAX_STEPS = 10000
PHASE_START = 1

# Rewards
REWARD_SURVIVAL = 0.1
REWARD_ENEMY_KILL = 10
REWARD_SPAWNER_DESTROY = 50
REWARD_PHASE_COMPLETE = 100
REWARD_DAMAGE_TAKEN = -10
REWARD_DEATH = -200

# Colors for objects
COLOR_BG = (10, 10, 25)
COLOR_GRID = (30, 30, 60)
COLOR_PLAYER = (0, 255, 200)
COLOR_ENEMY = (255, 50, 50)
COLOR_SPAWNER = (200, 0, 200)
COLOR_BULLET = (255, 255, 100)
COLOR_UI = (200, 200, 200)

# Particle colors
COLOR_EXPLOSION_ENEMY = (255, 100, 0)
COLOR_EXPLOSION_SPAWNER = (255, 0, 255)
COLOR_EXPLOSION_PLAYER = (83, 83, 83)
COLOR_EXPLOSION_PHASE = (0, 255, 255)
COLOR_THRUST = (100, 200, 255)
COLOR_SPAWN = (255, 0, 255)

# Particle settings
PARTICLE_EXPLOSION_COUNT_SMALL = 5
PARTICLE_EXPLOSION_COUNT_MEDIUM = 20
PARTICLE_EXPLOSION_COUNT_LARGE = 40
PARTICLE_EXPLOSION_COUNT_PLAYER = 30
PARTICLE_EXPLOSION_COUNT_PHASE = 30
PARTICLE_SPAWN_COUNT = 10
PARTICLE_MIN_LIFE = 20
PARTICLE_MAX_LIFE = 40
PARTICLE_THRUST_LIFE = 15

# Asset paths
ASSETS_PATH = "assets"
BACKGROUND_IMAGE = "background.png"
PLAYER_SHIP_IMAGE = "player_ship.png"
ENEMY_SHIP_IMAGE = "enemy_ship.png"
SPAWNER_IMAGE = "spawner.png"
BULLET_IMAGE = "bullet.png"

# Observation space size
OBSERVATION_SIZE = 11
# [player_x, player_y, player_vx, player_vy, player_angle,
#  nearest_enemy_dist, nearest_enemy_angle,
#  nearest_spawner_dist, nearest_spawner_angle,
#  player_health, current_phase]

# Action space sizes
ACTION_SPACE_ROTATION = 5  # no-op, thrust, rotate_left, rotate_right, shoot
ACTION_SPACE_DIRECTIONAL = 6  # no-op, up, down, left, right, shoot

# Control schemes
CONTROL_ROTATION = "rotation"
CONTROL_DIRECTIONAL = "directional"
